apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bamboo-pvc
  labels:
    app: bamboo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
